version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: expensetracker
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/database_export.sql:/docker-entrypoint-initdb.d/database_export.sql

  currency_converter_api:
    build:
      context: .
      dockerfile: currency-converter-Dockerfile
    ports:
      - "8000:8000"
    container_name: currency_converter_api_container

  mock_ads_api:
    build:
      context: .
      dockerfile: mock-ads-Dockerfile
    ports:
      - "8888:8000"
    container_name: mock_ads_api_container

volumes:
  mysql_data: